version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:Z
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ci4
      MYSQL_USER: ciuser
      MYSQL_PASSWORD: cipass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
